import type { Employee } from '../types/employee'

export const departments = ['All', 'Engineering', 'Design', 'QA']

export const employees: Employee[] = [
  {
    id: 1,
    name: 'Akhil R',
    designation: 'Software Engineer',
    department: 'Engineering',
    experience: 12,
    skills: ['Vue.js', 'React', 'Angular', 'TypeScript', 'Laravel', 'Tailwind CSS'],
    status: true,
    basicSalary: 50000,
    hra: 10000,
    da: 5000,
    bonus: 2000,
    tax: 10,
  },
  {
    id: 2,
    name: 'Abhilash',
    designation: 'UI/UX Designer',
    department: 'Design',
    experience: 10,
    status: true,
    skills: ['Figma', 'Adobe XD', 'Illustrator'],
    basicSalary: 40000,
    hra: 8000,
    da: 4000,
    bonus: 1500,
    tax: 10,
  },
  {
    id: 3,
    name: 'Nithin S',
    designation: 'Backend Developer',
    department: 'Engineering',
    experience: 7,
    status: false,
    skills: ['Laravel', 'MySQL', 'Redis'],
    basicSalary: 45000,
    hra: 9000,
    da: 4500,
    bonus: 1800,
    tax: 10,
  },
  {
    id: 4,
    name: 'Asha',
    designation: 'QA Engineer',
    department: 'QA',
    experience: 2,
    status: true,
    skills: ['Cypress', 'Vitest', 'Playwright'],
    basicSalary: 35000,
    hra: 7000,
    da: 3500,
    bonus: 1200,
    tax: 10,
  },
]
