import type { CartItem, Product } from '../types/product'

export const products: Product[] = [
  {
    id: 1,
    name: 'Wireless Mouse',
    description: 'A high-precision wireless mouse with ergonomic design.',
    price: 25,
    category: 'Electronics',
    imageUrl: 'https://example.com/images/wireless-mouse.jpg',
    stock: 100,
    createdAt: new Date('2023-01-15T10:00:00Z'),
    updatedAt: new Date('2023-01-20T12:00:00Z'),
  },
  {
    id: 2,
    name: 'Mechanical Keyboard',
    description: 'A durable mechanical keyboard with customizable RGB lighting.',
    price: 75,
    category: 'Electronics',
    imageUrl: 'https://example.com/images/mechanical-keyboard.jpg',
    stock: 50,
    createdAt: new Date('2023-02-10T14:30:00Z'),
    updatedAt: new Date('2023-02-15T09:45:00Z'),
  },
  {
    id: 3,
    name: 'USB-C Hub',
    description: 'A versatile USB-C hub with multiple ports for connectivity.',
    price: 35,
    category: 'Electronics',
    imageUrl: 'https://example.com/images/usb-c-hub.jpg',
    stock: 75,
    createdAt: new Date('2023-03-05T08:15:00Z'),
    updatedAt: new Date('2023-03-10T11:20:00Z'),
  },
  {
    id: 4,
    name: 'Webcam',
    description: 'A high-definition webcam for video conferencing and streaming.',
    price: 50,
    category: 'Electronics',
    imageUrl: 'https://example.com/images/webcam.jpg',
    stock: 30,
    createdAt: new Date('2023-04-01T16:45:00Z'),
    updatedAt: new Date('2023-04-05T13:10:00Z'),
  },
  {
    id: 5,
    name: 'Noise-Cancelling Headphones',
    description: 'Over-ear headphones with active noise cancellation for immersive sound.',
    price: 120,
    category: 'Electronics',
    imageUrl: 'https://example.com/images/noise-cancelling-headphones.jpg',
    stock: 40,
    createdAt: new Date('2023-05-12T11:00:00Z'),
    updatedAt: new Date('2023-05-15T14:30:00Z'),
  },
  {
    id: 6,
    name: 'Smartwatch',
    description: 'A sleek smartwatch with fitness tracking and notification features.',
    price: 150,
    category: 'Electronics',
    imageUrl: 'https://example.com/images/smartwatch.jpg',
    stock: 60,
    createdAt: new Date('2023-06-20T09:30:00Z'),
    updatedAt: new Date('2023-06-25T12:15:00Z'),
  },
]

export const cartItems: CartItem[] = [
  {
    id: 1,
    name: 'Wireless Mouse',
    price: 25,
    quantity: 1,
  },
  {
    id: 4,
    name: 'Webcam',
    price: 50,
    quantity: 1,
  },
]
